spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflowdb
    username: root
    password: dung2309
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: password

api:
  endpoint:
    base-url: /api/v1