spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflowdb
    username: root
    password: dung2309
    hikari:
      pool-name: app-pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: true
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: password

api:
  endpoint:
    base-url: /api/v1