ALTER TABLE answers
DROP
FOREIGN KEY FK_ANSWERS_ON_USER3JjJ40;

CREATE TABLE images
(
    id        BIGINT AUTO_INCREMENT NOT NULL,
    name      VARCHAR(255) NULL,
    type      VARCHAR(255) NULL,
    data      BLOB NULL,
    answer_id BIGINT NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE;

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answers (id) ON DELETE CASCADE;